services:
  database:
    image: postgres:18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.5
    command: [ 'start-dev --http-relative-path /auth' ]
    environment:
      - KEYCLOAK_ADMIN=keycloak
      - KEYCLOAK_ADMIN_PASSWORD=keycloak
